#ifndef __FORMULA_ERROR_H__
#define __FORMULA_ERROR_H__

#include <string>

enum FormulaError {
  NONE, PREFIX, TOKENIZATION, PARSE,
  CONSTANT_VIOLATION, PARAMETER_VIOLATION, EXPRESSION_VIOLATION, FUNCTION_VIOLATION, 
  INVALID_DEPENDENCY, UNRESOLVABLE_DEPENDENCY, DNE_DEPENDENCY
};

std::string formulaErrorString(FormulaError es);

#endif
